stages:
  get_features:
    cmd: python3 scripts/data-processing/get_features.py data/raw/Train
    deps:
    - data/raw/Train
    - scripts/data-processing/get_features.py
    outs:
    - data/stage1
  fill_na:
    cmd: python3 scripts/data-processing/fill_na.py data/stage1/train.csv
    deps:
    - data/stage1/train.csv
    - scripts/data-processing/fill_na.py
    outs:
    - data/stage2
  split:
    cmd: python3 scripts/data-processing/train_test_split.py data/stage2/train.csv
    deps:
    - data/stage2/train.csv
    - scripts/data-processing/train_test_split.py
    params:
    - split.split_ratio
  train:
    cmd: python3 scripts/model_learning/dt.py data/stage3/train.csv model.pkl
    deps:
    - data/stage3/train.csv
    - scripts/model_learning/dt.py
    params:
    - train.max_depth
    - train.seed
    outs:
    - models/model.pkl
  evaluate:
    cmd: python3 scripts/model_learning/evaluate.py data/stage3/test.csv models/model.pkl
    deps:
    - data/stage3/test.csv
    - models/model.pkl
    - scripts/model_learning/evaluate.py
    metrics:
    - evaluate/score.json:
        cache: false
